n = size(LWT.A,2);       % system states number
m = size(LWT.B,2);       % system input dimention
o = size(LWT.C,1);       % system output dimention
f = size(LWT.Cy,1);       % system feedback dimention
p=size(Exo.S1,2);                     % order of the disturbance Exo system
q=size(Exo.S2,2);                     % order of the Reference Exo system


cellInfo1 = { ... 
  { ... 
    'LinSysABCD', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'A', [n n], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'B', [n m], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'B_d', [n m], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'C', [o n], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'D', [o m], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Cy', [f n], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Dy', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Ts', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 
Simulink.Bus.cellToObject(cellInfo1)

cellInfo2 = { ... 
  { ... 
    'ExoSystem', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'S1', [p p], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'L1', [1 p], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'S2', [q q], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'L2', [o q], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...

    } ...
  } ...
}'; 
Simulink.Bus.cellToObject(cellInfo2)

cellInfo3 = { ... 
  { ... 
    'TmpStruct', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'X', [1 1], 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 
Simulink.Bus.cellToObject(cellInfo3)



 clear cellInfo1 cellInfo2 cellInfo3 n m p  q o


% l = Simulink.Bus.createObject(LWT)
% Simulink.Bus.createObjectFromVarStruct(LWT, 'he')